# Generated by Django 5.0 on 2023-12-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_discount_product_discount_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_start_date',
        ),
    ]
