# Generated by Django 5.0 on 2023-12-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'small'), ('medium', 'medium'), ('large', 'large')], default='Small', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pizzasize'),
        ),
    ]
