# Generated by Django 5.0 on 2023-12-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pizzasize_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_discount_price',
        ),
    ]
