# Generated by Django 5.0 on 2023-12-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_in_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
